# Script: 10a_plot_z_sky_mean.py
# Description: Visualizes the mean redshift from z_sky_mean.csv as a sky map and checks for isotropy.
# Author: Automatically generated by Grok 3 (xAI), modified by MSM
# Date: 2025-07-07
# Version: 1.1

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from datetime import datetime
import csv

def main():
    df = pd.read_csv("z_sky_mean.csv")

    ra_vals = sorted(set(df["ra_min"]))
    dec_vals = sorted(set(df["dec_min"]))
    ra_bins = len(ra_vals)
    dec_bins = len(dec_vals)

    z_mean_map = np.full((dec_bins, ra_bins), np.nan)
    for _, row in df.iterrows():
        i = dec_vals.index(row["dec_min"])
        j = ra_vals.index(row["ra_min"])
        z_mean_map[i, j] = row["mean_z"]

    flat_z = z_mean_map[~np.isnan(z_mean_map)]
    z_min, z_max = np.min(flat_z), np.max(flat_z)
    z_mean = np.mean(flat_z)
    z_std = np.std(flat_z)

    # Hemisphären-Isotropieanalyse
    north_mask = df["dec_min"] > 0
    south_mask = df["dec_min"] < 0
    z_north = df[north_mask]["mean_z"].dropna()
    z_south = df[south_mask]["mean_z"].dropna()
    z_mean_north = np.mean(z_north) if len(z_north) > 0 else np.nan
    z_std_north = np.std(z_north) if len(z_north) > 0 else np.nan
    z_mean_south = np.mean(z_south) if len(z_south) > 0 else np.nan
    z_std_south = np.std(z_south) if len(z_south) > 0 else np.nan

    print(f"Isotropy check:")
    print(f"  z̄ min  = {z_min:.3f}")
    print(f"  z̄ max  = {z_max:.3f}")
    print(f"  z̄ mean = {z_mean:.3f}")
    print(f"  z̄ std  = {z_std:.3f}")
    print(f"  North mean = {z_mean_north:.3f}, std = {z_std_north:.3f}")
    print(f"  South mean = {z_mean_south:.3f}, std = {z_std_south:.3f}")

    ra_min = min(ra_vals)
    ra_max = max(df["ra_max"])
    dec_min = min(dec_vals)
    dec_max = max(df["dec_max"])

    plt.figure(figsize=(12, 6))
    cmap = plt.cm.plasma
    cmap.set_bad("lightgrey")

    im = plt.imshow(
        np.flipud(z_mean_map),
        extent=[ra_min, ra_max, dec_min, dec_max],
        aspect='auto',
        cmap=cmap,
        interpolation='none'
    )
    plt.colorbar(im, label='Mean Redshift $\\bar{z}$')
    plt.xlabel('Right Ascension (RA) [°]')
    plt.ylabel('Declination (DEC) [°]')
    plt.title('Mean Redshift by Sky Regions')
    plt.grid(False)
    plt.tight_layout()

    try:
        os.makedirs("img", exist_ok=True)
    except Exception as e:
        print(f"Warning: Could not create 'img' directory: {e}")

    plt.savefig("img/10a_z_sky_mean_map.png")

    # Update results.csv
    results_path = "results.csv"
    script_id = "10a_plot_z_sky_mean.py"
    try:
        rows = []
        if os.path.exists(results_path):
            with open(results_path, "r", encoding="utf-8") as f:
                reader = csv.reader(f)
                rows = list(reader)
            header, *data_rows = rows
            data_rows = [row for row in data_rows if row[0] != script_id]
        else:
            header = ["script", "parameter", "value", "target", "deviation", "timestamp"]
            data_rows = []

        timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
        new_rows = [
            [script_id, "z_mean_min", z_min, "", "", timestamp],
            [script_id, "z_mean_max", z_max, "", "", timestamp],
            [script_id, "z_mean_avg", z_mean, "N/A", "N/A", timestamp],
            [script_id, "z_mean_std", z_std, "ideal ≈ 0 (isotrop)", "N/A", timestamp],
            [script_id, "z_mean_north", z_mean_north, "", "", timestamp],
            [script_id, "z_mean_south", z_mean_south, "", "", timestamp],
            [script_id, "z_std_north", z_std_north, "", "", timestamp],
            [script_id, "z_std_south", z_std_south, "", "", timestamp],
        ]

        with open(results_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(header)
            writer.writerows(data_rows + new_rows)

    except Exception as e:
        print(f"Error updating results.csv: {e}")

    # Summary log
    with open("z_sky_isotropy_summary.txt", "w", encoding="utf-8") as f:
        f.write("Isotropy check:\n")
        f.write(f"z̄ min  = {z_min:.6f}\n")
        f.write(f"z̄ max  = {z_max:.6f}\n")
        f.write(f"z̄ mean = {z_mean:.6f}\n")
        f.write(f"z̄ std  = {z_std:.6f}\n")
        f.write(f"North mean = {z_mean_north:.6f}, std = {z_std_north:.6f}\n")
        f.write(f"South mean = {z_mean_south:.6f}, std = {z_std_south:.6f}\n")

if __name__ == "__main__":
    main()
